version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - libgirepository1.0-dev
    - gcc
    - libcairo2-dev
    - pkg-config
    - python3-dev
    - gir1.2-gtk-3.0
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
   - requirements: docs/requirements.txt