[tool.poetry]
name = "wanikani-cli"
version = "0.1.1"
description = "WaniKani command line interface"
authors = ["Augustin <ajitekun@gmail.com>"]
readme = "README.rst"
license = "MIT"
homepage = "https://github.com/ajite/wanikani-cli"
repository = "https://github.com/ajite/wanikani-cli"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
romkan = "^0.2.1"
ascii-magic = "^1.6"
Pillow = "^9.1.0"
playsound = "^1.3.0"
pyobjc = {version = "^8.5", platform = "darwin"}
coverage = "^6.3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wanikani-cli = 'wanikani_cli.wanikani:main'